apiVersion: v1
kind: PersistentVolume
metadata:
  name: u84u-server-pv
  namespace: u84u
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
