apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: u84u-docker-data-pvc
  namespace: u84u
spec:
  storageClassName: default
  volumeName: u84u-docker-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
